### ISSUE TITLE
NativeScript 7 Support

### ISSUE THREAD

**Issue by jcassidyav** [edusperoni/nativescript-ng-ripple#10]
Will this plugin be updated to support Nativescript 7.X?

Thanks.

**Comment by edusperoni** [comment]
@jcassidyav hey! Yes it will. I think I'll take over nativescript-ripple so it might be under a different name but I'll keep you posted

**Comment by jcassidyav** [comment]
Great that is good news, Thanks !

**Comment by fernandomeneghetti** [comment]
Estava tentando atualizar para o 7 aqui. Deu estouro também. Os estagiários estão de folga? Da para mandar um serviço via trabalho remoto pra eles! hehehe

**Comment by edusperoni** [comment]
Please use nativescript-ripple: https://github.com/edusperoni/nativescript-ripple
